#!/usr/bin/env bun

import { renderMermaidSVG } from "beautiful-mermaid";
import { mkdir, readFile, writeFile } from "fs/promises";
import { resolve, dirname } from "path";

interface RenderOptions {
  sourcePath: string;
  outputPath: string;
  title?: string;
  darkMode?: boolean;
}

const DEFAULT_OPTIONS: Required<Omit<RenderOptions, "sourcePath" | "outputPath">> = {
  title: "Mermaid Diagram",
  darkMode: true,
};

export async function renderMermaidFile(options: RenderOptions): Promise<void> {
  const { sourcePath, outputPath, title, darkMode } = { ...DEFAULT_OPTIONS, ...options };

  const sourceContent = await readFile(sourcePath, "utf-8");
  const mermaidSource = extractMermaid(sourceContent);

  const svg = renderMermaidSVG(mermaidSource, {
    bg: darkMode ? "#16213e" : "#ffffff",
    fg: darkMode ? "#a9b1d6" : "#333333",
    transparent: false,
  });

  const html = wrapHtml({ svg, title, darkMode });

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, html);

  console.log(`Rendered: ${sourcePath} -> ${outputPath}`);
}

function extractMermaid(content: string): string {
  const fencedMatch = content.match(/```mermaid\n([\s\S]*?)```/);
  if (fencedMatch) {
    return fencedMatch[1]!.trim();
  }
  const lines = content.split("\n");
  const mermaidIndex = lines.findIndex((line) => line.startsWith("mermaid"));
  if (mermaidIndex !== -1) {
    return lines.slice(mermaidIndex + 1).join("\n").trim();
  }
  return content.trim();
}

interface WrapHtmlOptions {
  svg: string;
  title: string;
  darkMode: boolean;
}

function wrapHtml(options: WrapHtmlOptions): string {
  const { svg, title, darkMode } = options;
  const bg = darkMode ? "#1a1a2e" : "#f5f5f5";
  const textColor = darkMode ? "#eee" : "#333";
  const linkColor = darkMode ? "#00d9ff" : "#0066cc";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 2rem; background: ${bg}; color: ${textColor}; }
    h1 { color: ${linkColor}; }
    .container { max-width: 1400px; margin: 0 auto; }
    .diagram { background: ${darkMode ? "#16213e" : "#ffffff"}; padding: 1rem; border-radius: 8px; margin: 1rem 0; }
    .footer { margin-top: 2rem; font-size: 0.875rem; color: ${darkMode ? "#888" : "#666"}; }
    a { color: ${linkColor}; }
  </style>
</head>
<body>
  <div class="container">
    <h1>${title}</h1>
    <div class="diagram">
      ${svg}
    </div>
    <div class="footer">
      Generated by <a href="https://github.com/lukilabs/beautiful-mermaid">beautiful-mermaid</a>
    </div>
  </div>
</body>
</html>`;
}

if (import.meta.main) {
  const args = Bun.argv.slice(2);

  if (args.length < 2) {
    console.error("Usage: bun render-mermaid.ts <source.md> <output.html> [title]");
    console.error("  Renders a Mermaid diagram from a markdown file to a standalone HTML.");
    process.exit(1);
  }

  const [sourcePath, outputPath, title] = args;

  await renderMermaidFile({
    sourcePath: resolve(sourcePath),
    outputPath: resolve(outputPath),
    title: title || DEFAULT_OPTIONS.title,
    darkMode: DEFAULT_OPTIONS.darkMode,
  });
}
